
<a class="btn btn-success" href="<?php echo $this->url(array('controller'=>'organizations','action'=>'addnew'));?>"><i class="icon-success-sign icon-white"></i>Add new</a>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Organizations managament (page: <?php echo $this->paginator->getCurrentPageNumber().' / '.$this->paginator->getPages()->pageCount;?>) </div>
  <div class="panel-body">
    <p>This is Zend paginator with <?php echo $this->paginator->getItemCountPerPage(); ?> items per page
    </p>
  </div>

  <!-- Table -->
  <table class="table">
      <thead>
          <tr><th>Internal ID</th><th>Name</th><th>City</th><th>Status</th><th>Creator</th><th></th></tr>
      </thead>
      <?php
      $items=$this->paginator->getCurrentItems();
      
      foreach($items as $key=>$value){
          
          echo sprintf('<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td><a href="%s/byid/%s">edit</a></td></tr>',
                  $value['organization_id'], $value['name'], $value['city'],
                  ($value['status'] == 1)? 'Active':'Inactive',
                  $value['email'].' ('.$value['fname'].' '.$value['lname'].')',
                  $this->url(array('controller' =>'organizations', 'action'=>'editexternal')), $value['organization_id']);
      }
        ?>
  </table>
</div>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'paginatecontrol.phtml'); ?>
